### ISSUE TITLE
Add about page link to navbar

### ISSUE THREAD

**Issue by streamerd** [resonatecoop/website#27]
hello,

currently, /about page is only accessible through links at /listen page via a button @ footer.
details on coop is quite important, working as guiding ways to co-ops // cool stuff like this.

would be cool to see on top of the page. it was there once, believing it's worth including there again //

**Comment by caprenter** [comment]
It looks to me like this is implemented in the 'future website' which this repository is all about.
About can be found in the Learn drop down in the header and in the footer.

There is an about link in the footer of the current live site (which I think is the legacy wordpress (my words!) )but not in the header, which may be what the ask is about.

**Comment by peterklingelhofer** [comment]
Based on our latest figma, we are planning to remove the About page entirely: https://github.com/resonatecoop/website/pull/46, since this copy is covered in a more concise manner on the main page and co-op and pricing pages.
