### ISSUE TITLE
Comments on the UI

### ISSUE THREAD

**Issue by giraffekey** [resonatecoop/website#5]
I think the Join Us button is too close to the + button. It's also vertically centered weirdly.

![image](https://user-images.githubusercontent.com/11844126/98390672-8ea6f400-200a-11eb-9abf-71c538cd6da9.png)

I think it may look better if the nav links were in the center of the header. And maybe more vertically centered though if the spacing between them were increased that may not be necessary.

**Comment by giraffekey** [comment]
Also here:

![image](https://user-images.githubusercontent.com/11844126/98391224-37555380-200b-11eb-8f67-f03f2264cc66.png)

The resonate logo looks too far left to me and is there is too much spacing between it and the footer links.

These all seem easily fixable so lemme know if you agree with my critiques and I will fix them myself.

**Comment by giraffekey** [comment]
As an alternative to centering the nav items the spacing between items can be decreased and the spacing between Join Us and + could be made to match the new spacing between About and Pricing.

**Comment by auggod** [comment]
Feel free to send a pull request! Everything is still considered as work in progress right now and we're quite open to critiques too.

It would help a lot if the designs (figma) were available on github so volunteers can get an idea of how it might look.

**Comment by rrriiiyyyaaa** [comment]
I want to work on this issue

**Comment by auggod** [comment]
This issue should have been closed by now. We're working on a new UI for the website. See #14.
