### ISSUE TITLE
about page missing

### ISSUE THREAD

**Issue by laroche** [resonatecoop/website#65]
The "about" web-page gives a 404 error code.

**Comment by peterklingelhofer** [comment]
Thanks for reporting @laroche! Guessing you're referring to the https://stream.resonate.coop About link - fix has been merged [here](https://github.com/resonatecoop/stream/pull/277) but deploying changes is [a bit tricky right now](https://community.resonate.coop/t/minimal-mobile-apps-for-android-and-ios/2613/150).

**Comment by simonv3** [comment]
@peterklingelhofer https://resonate.coop/about (linked from the footer on resonate.coop) leads to a 404. 

We should actually be able to fix that one.

**Comment by peterklingelhofer** [comment]
Good point @simonv3. I would expect this 'About' link to appear here: https://github.com/resonatecoop/id/blob/cdea90aebc69009c4842ea91ee7fe960945b3519/web/layouts/outside.html#L88, but it was removed, peculiar that it's still visible on the live site. I'll keep digging.

**Comment by simonv3** [comment]
I think this https://github.com/resonatecoop/website/pull/59 was just never released

**Comment by simonv3** [comment]
Okay fixed by deploying the most recent version
