### ISSUE TITLE
Contact Feature Does Not Work

### ISSUE THREAD

**Issue by Justin-Lund** [resonatecoop/website#66]
When using the contact/support feature, when you hit "send", nothing happens.
It's also worth noting that the form limits text to an extreme amount to the point that I couldn't type out my actual issue in the contact form.

**Comment by auggod** [comment]
I found that the mailer is still configured with the old mailgun api key. It was changed around September and I forgot about it. Now, I have updated the key. 

Anyway, I suggest we drop this feature.
